### ISSUE TITLE
Fork the Repo

### ISSUE THREAD

**Issue by SquidDev** [lupus590/CCDoc#2]
Why don't you just fork the original repo? Then you can back-merge in fixes from the original repo and you don't have to duplicate code. Most of the code will be identical to the original.

You will also have to copy some things from Penlight (https://github.com/stevedonovan/Penlight).

**Comment by lupus590** [comment]
I tend to do things the hard way.

**Comment by SquidDev** [comment]
You can't set the fork after you've created it. Generally if you delete this and just refork it. The alternative would be to set the original as a remote and pull from it.

**Comment by lupus590** [comment]
I'll just copy and paste.
